[package]
name = "ra-multiplex"
version = "0.1.2"
description = "share one rust-analyzer server instance between multiple LSP clients to save resources"
documentation = "https://docs.rs/ra-multiplex"
repository = "https://github.com/pr2502/ra-multiplex"
license = "MIT"
edition = "2021"
autobins = false

[[bin]]
name = "ra-multiplex"
path = "src/client.rs"

[[bin]]
name = "ra-multiplex-server"
path = "src/server.rs"

[dependencies]
anyhow = "1.0.53"
env_logger = "0.9.0"
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "sync", "time", "macros", "net", "io-util", "io-std", "process"] }
